In [1]:
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor

In [2]:
df = pd.read_csv("dataframe-auditoria-small-with-anomalies.csv")
df.drop(columns=['Unnamed: 0'],inplace=True)
print(df.shape)
df.head()

(100000, 22)

,IP1,IP2,IP3,IP4,IP5,IP6,IP7,IP8,IP9,IP10,...,CPF3,CPF4,CPF5,CPF6,CPF7,CPF8,CPF9,CPF10,qtd_access_ip_last_days,qtd_access_cpf_last_days
0,1.0,5.0,-1.0,-1.0,0.0,0.0,0.0,-3.0,0.0,-1.0,...,-4.0,-1.0,0.0,0.0,0.0,0.0,1.0,-2.0,1,2
1,4.0,3.0,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.0,...,-2.0,-1.0,0.0,0.0,0.0,-1.0,0.0,-1.0,1,2
2,3.0,2.0,0.0,-1.0,0.0,0.0,0.0,-2.0,0.0,-4.0,...,-3.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,1,3
3,2.0,5.0,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.0,...,-3.0,-2.0,0.0,0.0,0.0,0.0,1.0,-1.0,1,2
4,1.0,3.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,-6.0,...,-2.0,-3.0,0.0,0.0,0.0,-1.0,0.0,-1.0,1,5

In [3]:
clf = LocalOutlierFactor(novelty=True,contamination=0.07)
clf = clf.fit(df)

In [4]:
y_pred = clf.predict(df)
y_pred = pd.Series(y_pred)
df['cluster'] = y_pred

In [5]:
df.head()

,IP1,IP2,IP3,IP4,IP5,IP6,IP7,IP8,IP9,IP10,...,CPF4,CPF5,CPF6,CPF7,CPF8,CPF9,CPF10,qtd_access_ip_last_days,qtd_access_cpf_last_days,cluster
0,1.0,5.0,-1.0,-1.0,0.0,0.0,0.0,-3.0,0.0,-1.0,...,-1.0,0.0,0.0,0.0,0.0,1.0,-2.0,1,2,1
1,4.0,3.0,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.0,...,-1.0,0.0,0.0,0.0,-1.0,0.0,-1.0,1,2,1
2,3.0,2.0,0.0,-1.0,0.0,0.0,0.0,-2.0,0.0,-4.0,...,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,1,3,1
3,2.0,5.0,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.0,...,-2.0,0.0,0.0,0.0,0.0,1.0,-1.0,1,2,1
4,1.0,3.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,-6.0,...,-3.0,0.0,0.0,0.0,-1.0,0.0,-1.0,1,5,1

In [6]:
df.cluster.value_counts()

 1    94015
-1     5985
Name: cluster, dtype: int64

In [7]:
df[df.cluster==-1].head(10)

,IP1,IP2,IP3,IP4,IP5,IP6,IP7,IP8,IP9,IP10,...,CPF4,CPF5,CPF6,CPF7,CPF8,CPF9,CPF10,qtd_access_ip_last_days,qtd_access_cpf_last_days,cluster
28,3.0,2.0,0.0,-3.0,0.0,0.0,0.0,-4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1,3,-1
93,4.0,3.0,-1.0,0.0,0.0,0.0,0.0,-4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,-4.0,1,13,-1
95,2.0,7.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-3.0,0.0,-2.0,1,4,-1
101,2.0,1.0,0.0,-2.0,0.0,0.0,0.0,-4.0,0.0,-3.0,...,-1.0,0.0,0.0,0.0,0.0,4.0,-1.0,6,25,-1
161,1.0,1.0,-1.0,-1.0,0.0,0.0,0.0,-5.0,1.0,-2.0,...,-1.0,0.0,0.0,0.0,0.0,4.0,-1.0,3,25,-1
187,0.0,7.0,0.0,-2.0,0.0,0.0,0.0,-2.0,0.0,-1.0,...,-1.0,0.0,0.0,0.0,0.0,3.0,0.0,1,6,-1
204,3.0,4.0,0.0,0.0,0.0,0.0,0.0,-4.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,-4.0,1.0,0.0,3,1,-1
205,1.0,3.0,0.0,-1.0,0.0,0.0,0.0,-1.0,0.0,-6.0,...,-6.0,0.0,0.0,0.0,-1.0,0.0,-2.0,6,3,-1
214,1.0,7.0,0.0,0.0,0.0,0.0,0.0,-3.0,0.0,-1.0,...,-1.0,0.0,0.0,0.0,0.0,1.0,0.0,3,12,-1
259,2.0,2.0,0.0,-3.0,0.0,0.0,0.0,-2.0,0.0,-3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,1,8,-1

In [11]:
df[101:102].drop(columns=['cluster'])

,IP1,IP2,IP3,IP4,IP5,IP6,IP7,IP8,IP9,IP10,...,CPF3,CPF4,CPF5,CPF6,CPF7,CPF8,CPF9,CPF10,qtd_access_ip_last_days,qtd_access_cpf_last_days
101,2.0,1.0,0.0,-2.0,0.0,0.0,0.0,-4.0,0.0,-3.0,...,-1.0,-1.0,0.0,0.0,0.0,0.0,4.0,-1.0,6,25

In [12]:
clf.predict(df[101:102].drop(columns=['cluster']))

array([-1])

In [10]:
df.to_csv('dataframe-auditoria-small-with-anomalies-clustered.csv')